# Resource for centos specification slave pods
apiVersion: v1
kind: Service
metadata:
  name: x86-centos-slaves-service
  namespace: jenkins
  labels:
    app: x86-centos-slaves
spec:
  ports:
    - port: 80
      name: port-placeholder
  clusterIP: None
  selector:
    app: x86-centos-slaves
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: x86-centos-slaves
  namespace: jenkins
  labels:
    app: x86-centos-slaves
spec:
  serviceName: x86-centos-slaves-service
  replicas: 96
  selector:
    matchLabels:
      app: x86-centos-slaves
  template:
    metadata:
      labels:
        app: x86-centos-slaves
    spec:
      imagePullSecrets:
        - name: huawei-swr-image-pull-secret
      nodeSelector:
        centos: "true"
      initContainers:
        - name: slave-init
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/jenkins-slave-tools-x86:v0.0.1.20210729
          volumeMounts:
            - mountPath: /home/jenkins/share-config
              name: jenkins-share-config
          env:
            - name: JENKINS_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_USER_NAME
              value: admin
            - name: JENKINS_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jenkins-secret
                  key: password
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/agent-working-dir
            - name: JENKINS_URL
              value: http://192.168.0.231:30080
            - name: JENKINS_SHARE_FOLDER
              value: /home/jenkins/share-config
            - name: EXECUTOR_NUMBERS
              value: "1"
            - name: NODE_LABELS
              value: x86 x86-build-centos
          args: ["$(JENKINS_URL)", "$(JENKINS_USER_NAME)", "$(JENKINS_USER_PASSWORD)", "$(JENKINS_NODE_NAME)", "$(EXECUTOR_NUMBERS)", "$(JENKINS_AGENT_WORKDIR)", "$(NODE_LABELS)", "$(JENKINS_SHARE_FOLDER)"]
      containers:
        - name: jenkins-slave
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/mindspore_centos_x86:centos7.9.2009-20230130
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /home/jenkins/agent-working-dir
              name: centos-workspace-pvc
            - mountPath: /home/jenkins/share-config
              name: jenkins-share-config
            - mountPath: /home/jenkins/share-data
              name: jenkins-share-data
            - mountPath: /dev/shm
              name: jenkins-share-memory
          command:
            - /bin/sh
            - -c
            - |
              export JENKINS_SECRET=`cat /home/jenkins/share-config/node_secret.id`;
              exec /tini -- jenkins-agent
          resources:
            requests:
              cpu: 14000m
              memory: 56Gi
            limits:
              cpu: 16000m
              memory: 58Gi
          env:
            - name: JENKINS_TUNNEL
              value: 192.168.0.231:30500
            - name: JENKINS_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/agent-working-dir
            - name: JENKINS_URL
              value: http://192.168.0.231:30080
      volumes:
        - name: jenkins-share-config
          emptyDir: {}
        - name: jenkins-share-memory
          emptyDir: 
            medium: Memory
            sizeLimit: 2Gi
        - name: jenkins-share-data
          persistentVolumeClaim:
            # NOTE: this persistvolumeclaim is imported on CCE web console, not created by command.
            claimName: cce-efs-import-share-volume-01
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: centos-workspace-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 200Gi
        storageClassName: "ssd"
